sudo: required

language: node_js

node_js:
  - "10"

install:
- npm install vuepress -g

script:
- git config -–global user.name "yhlben"  
- git config -–global user.email 'yinhengliben@gmail.com'
- npm run ci